---
- name: Install LizardFS cgiserver
  package:
    name: lizardfs-cgiserv
    state: installed

- name: Configure LizardFS cgiserver
  template:
    src: lizardfs-cgiserv.j2
    dest: /etc/default/lizardfs-cgiserv
    mode: 0644
  notify: reload lizardfs-cgiserver
